// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernIssues.Models.Entities;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernIssues.Database.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20251121215601_CreateBankTransactionsTable")]
    partial class CreateBankTransactionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernIssues.Models.Entities.BankTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Accountnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accountnumber");

                    b.Property<decimal>("Accumulated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("accumulated");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway");

                    b.Property<string>("Referencecode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("referencecode");

                    b.Property<string>("Subaccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subaccount");

                    b.Property<DateTime>("Transactiondate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("transactiondate");

                    b.Property<decimal>("Transferamount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("transferamount");

                    b.Property<string>("Transfertype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("transfertype");

                    b.HasKey("Id")
                        .HasName("bank_transactions_pkey");

                    b.ToTable("bank_transactions", (string)null);
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.cart", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.Property<int>("cart_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cart_id"));

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("price_at_add")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("user_id", "cart_id", "product_id")
                        .HasName("carts_pkey");

                    b.HasIndex("product_id");

                    b.ToTable("carts", t =>
                        {
                            t.HasComment("Giỏ hàng của khách hàng - mỗi dòng là 1 sản phẩm trong giỏ hàng");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<int?>("parent_id")
                        .HasColumnType("integer")
                        .HasComment("Tham chiếu đến danh mục cha (nếu có)");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.HasKey("category_id")
                        .HasName("categories_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("parent_id");

                    b.HasIndex("updated_by");

                    b.ToTable("categories", t =>
                        {
                            t.HasComment("Danh mục sản phẩm (ví dụ: Laptop, CPU, RAM, Phụ kiện,...)");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.faq", b =>
                {
                    b.Property<int>("faq_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("faq_id"));

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.HasKey("faq_id")
                        .HasName("faq_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("updated_by");

                    b.ToTable("faq", null, t =>
                        {
                            t.HasComment("Câu hỏi thường gặp (FAQ) của khách hàng");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.log", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("log_id"));

                    b.Property<string>("action_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("product_id")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("log_id")
                        .HasName("logs_pkey");

                    b.HasIndex("product_id");

                    b.HasIndex("user_id");

                    b.ToTable("logs", t =>
                        {
                            t.HasComment("Lưu lịch sử thao tác của người dùng: xem, thêm giỏ hàng, đăng nhập,...");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("order_id"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("order_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<decimal?>("total_amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<string>("types")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'COD'")
                        .HasComment("Loại thanh toán: COD, Transfer, ATM");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("order_id")
                        .HasName("orders_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("updated_by");

                    b.HasIndex("user_id");

                    b.ToTable("orders", t =>
                        {
                            t.HasComment("Thông tin đơn hàng của khách hàng");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.order_detail", b =>
                {
                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("image_url")
                        .HasColumnType("text")
                        .HasComment("Lưu ảnh sản phẩm tại thời điểm mua");

                    b.Property<decimal>("price_at_purchase")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Lưu tên sản phẩm tại thời điểm mua để giữ lịch sử");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.HasKey("order_id", "product_id")
                        .HasName("order_details_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("product_id");

                    b.HasIndex("updated_by");

                    b.ToTable("order_details", t =>
                        {
                            t.HasComment("Chi tiết các sản phẩm trong mỗi đơn hàng");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.product", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("product_id"));

                    b.Property<int?>("category_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("image_url")
                        .HasColumnType("text");

                    b.Property<bool?>("is_disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("on_prices")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<int?>("warranty_period")
                        .HasColumnType("integer");

                    b.HasKey("product_id")
                        .HasName("products_pkey");

                    b.HasIndex("category_id");

                    b.HasIndex("created_by");

                    b.HasIndex("updated_by");

                    b.ToTable("products", t =>
                        {
                            t.HasComment("Danh sách sản phẩm bán trong cửa hàng: laptop, linh kiện, phụ kiện...");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.product_serial", b =>
                {
                    b.Property<int>("serial_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("serial_id"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("import_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("is_disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Trạng thái bảo hành: false = còn bảo hành, true = hết bảo hành");

                    b.Property<bool?>("is_sold")
                        .HasColumnType("boolean");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<string>("serial_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.HasKey("serial_id")
                        .HasName("product_serials_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("product_id");

                    b.HasIndex("serial_number")
                        .IsUnique()
                        .HasDatabaseName("product_serials_serial_number_unique");

                    b.HasIndex("updated_by");

                    b.ToTable("product_serials", null, t =>
                        {
                            t.HasComment("Bảng quản lý serial numbers của sản phẩm trong kho");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.promotion", b =>
                {
                    b.Property<int>("promotion_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("promotion_id"));

                    b.Property<string>("banner_url")
                        .HasColumnType("text")
                        .HasComment("URL banner khuyến mãi (tùy chọn)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("discount_type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("percentage")
                        .HasComment("Loại khuyến mãi: percentage (phần trăm) hoặc fixed_amount (số tiền trực tiếp)");

                    b.Property<decimal?>("discount_value")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasComment("Giá trị khuyến mãi: phần trăm (0-100) hoặc số tiền (nếu discount_type = fixed_amount)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("promotion_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.HasKey("promotion_id")
                        .HasName("promotions_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("updated_by");

                    b.ToTable("promotions", t =>
                        {
                            t.HasComment("Chương trình khuyến mãi, ví dụ: giảm 10%, mua 1 tặng 1...");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.user", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("avatar_url")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool?>("email_confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("is_disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'customer'::character varying")
                        .HasComment("Phân quyền người dùng: customer hoặc admin");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("user_id")
                        .HasName("users_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("updated_by");

                    b.HasIndex(new[] { "email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasComment("Bảng lưu thông tin tài khoản người dùng (admin và customer)");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.warranty", b =>
                {
                    b.Property<int>("warranty_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("warranty_id"));

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("created_by")
                        .HasColumnType("integer");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("is_disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<string>("serial_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'active'::character varying");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("warranty_id")
                        .HasName("warranty_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.HasIndex("serial_number")
                        .IsUnique()
                        .HasDatabaseName("warranty_serial_number_unique");

                    b.HasIndex("updated_by");

                    b.HasIndex("user_id");

                    b.ToTable("warranty", null, t =>
                        {
                            t.HasComment("Thông tin bảo hành sản phẩm (thời gian và trạng thái)");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.warranty_detail", b =>
                {
                    b.Property<int>("detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("detail_id"));

                    b.Property<int>("claim_number")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("completed_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("cost")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime?>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("created_by")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("handled_by")
                        .HasColumnType("integer");

                    b.Property<string>("image_urls")
                        .HasColumnType("text")
                        .HasComment("Ảnh minh chứng (có thể lưu JSON array)");

                    b.Property<bool?>("is_disabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("request_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("service_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("solution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'pending'::character varying")
                        .HasComment("Trạng thái: pending, approved, processing, completed, rejected, cancelled");

                    b.Property<DateTime?>("updated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("updated_by")
                        .HasColumnType("integer");

                    b.Property<int>("warranty_id")
                        .HasColumnType("integer");

                    b.HasKey("detail_id")
                        .HasName("warranty_details_pkey");

                    b.HasIndex("created_by");

                    b.HasIndex("handled_by");

                    b.HasIndex("updated_by");

                    b.HasIndex("warranty_id", "claim_number")
                        .IsUnique()
                        .HasDatabaseName("warranty_details_warranty_claim_unique");

                    b.ToTable("warranty_details", null, t =>
                        {
                            t.HasComment("Chi tiết từng lần bảo hành của một warranty (lần 1, 2, 3, 4...)");
                        });
                });

            modelBuilder.Entity("product_promotion", b =>
                {
                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("promotion_id")
                        .HasColumnType("integer");

                    b.HasKey("product_id", "promotion_id")
                        .HasName("product_promotions_pkey");

                    b.HasIndex("promotion_id");

                    b.ToTable("product_promotions", null, t =>
                        {
                            t.HasComment("Liên kết nhiều sản phẩm với nhiều chương trình khuyến mãi");
                        });
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.cart", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.product", "product")
                        .WithMany("carts")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("carts_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "user")
                        .WithMany("carts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("carts_user_id_fkey");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.category", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("categorycreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("categories_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.category", "parent")
                        .WithMany("Inverseparent")
                        .HasForeignKey("parent_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("categories_parent_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("categoryupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("categories_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("parent");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.faq", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("faqcreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("faq_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("faqupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("faq_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.log", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.product", "product")
                        .WithMany("logs")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("logs_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "user")
                        .WithMany("logs")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("logs_user_id_fkey");

                    b.Navigation("product");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.order", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("ordercreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("orderupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_updated_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "user")
                        .WithMany("orderusers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("orders_user_id_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("updated_byNavigation");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.order_detail", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("order_detailcreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("order_details_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.order", "order")
                        .WithMany("order_details")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_details_order_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.product", "product")
                        .WithMany("order_details")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_details_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("order_detailupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("order_details_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("order");

                    b.Navigation("product");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.product", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.category", "category")
                        .WithMany("products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("products_category_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("productcreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("products_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("productupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("products_updated_by_fkey");

                    b.Navigation("category");

                    b.Navigation("created_byNavigation");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.product_serial", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("product_serialcreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("product_serials_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.product", "product")
                        .WithMany("product_serials")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_serials_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("product_serialupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("product_serials_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("product");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.promotion", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("promotioncreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("promotions_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("promotionupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("promotions_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.user", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("Inversecreated_byNavigation")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("Inverseupdated_byNavigation")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_updated_by_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("updated_byNavigation");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.warranty", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("warrantycreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("warranty_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.order", "order")
                        .WithMany("warranties")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("warranty_order_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.product", "product")
                        .WithMany("warranties")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("warranty_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.product_serial", "product_serial")
                        .WithMany()
                        .HasForeignKey("serial_number")
                        .HasPrincipalKey("serial_number")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("warrantyupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("warranty_updated_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "user")
                        .WithMany("warrantyusers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("warranty_user_id_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("order");

                    b.Navigation("product");

                    b.Navigation("product_serial");

                    b.Navigation("updated_byNavigation");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.warranty_detail", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.user", "created_byNavigation")
                        .WithMany("warranty_detailcreated_byNavigations")
                        .HasForeignKey("created_by")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("warranty_details_created_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "handled_byNavigation")
                        .WithMany("warranty_detailhandled_byNavigations")
                        .HasForeignKey("handled_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("warranty_details_handled_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.user", "updated_byNavigation")
                        .WithMany("warranty_detailupdated_byNavigations")
                        .HasForeignKey("updated_by")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("warranty_details_updated_by_fkey");

                    b.HasOne("ModernIssues.Models.Entities.warranty", "warranty")
                        .WithMany("warranty_details")
                        .HasForeignKey("warranty_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("warranty_details_warranty_id_fkey");

                    b.Navigation("created_byNavigation");

                    b.Navigation("handled_byNavigation");

                    b.Navigation("updated_byNavigation");

                    b.Navigation("warranty");
                });

            modelBuilder.Entity("product_promotion", b =>
                {
                    b.HasOne("ModernIssues.Models.Entities.product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_promotions_product_id_fkey");

                    b.HasOne("ModernIssues.Models.Entities.promotion", null)
                        .WithMany()
                        .HasForeignKey("promotion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("product_promotions_promotion_id_fkey");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.category", b =>
                {
                    b.Navigation("Inverseparent");

                    b.Navigation("products");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.order", b =>
                {
                    b.Navigation("order_details");

                    b.Navigation("warranties");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.product", b =>
                {
                    b.Navigation("carts");

                    b.Navigation("logs");

                    b.Navigation("order_details");

                    b.Navigation("product_serials");

                    b.Navigation("warranties");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.user", b =>
                {
                    b.Navigation("Inversecreated_byNavigation");

                    b.Navigation("Inverseupdated_byNavigation");

                    b.Navigation("carts");

                    b.Navigation("categorycreated_byNavigations");

                    b.Navigation("categoryupdated_byNavigations");

                    b.Navigation("faqcreated_byNavigations");

                    b.Navigation("faqupdated_byNavigations");

                    b.Navigation("logs");

                    b.Navigation("order_detailcreated_byNavigations");

                    b.Navigation("order_detailupdated_byNavigations");

                    b.Navigation("ordercreated_byNavigations");

                    b.Navigation("orderupdated_byNavigations");

                    b.Navigation("orderusers");

                    b.Navigation("product_serialcreated_byNavigations");

                    b.Navigation("product_serialupdated_byNavigations");

                    b.Navigation("productcreated_byNavigations");

                    b.Navigation("productupdated_byNavigations");

                    b.Navigation("promotioncreated_byNavigations");

                    b.Navigation("promotionupdated_byNavigations");

                    b.Navigation("warranty_detailcreated_byNavigations");

                    b.Navigation("warranty_detailhandled_byNavigations");

                    b.Navigation("warranty_detailupdated_byNavigations");

                    b.Navigation("warrantycreated_byNavigations");

                    b.Navigation("warrantyupdated_byNavigations");

                    b.Navigation("warrantyusers");
                });

            modelBuilder.Entity("ModernIssues.Models.Entities.warranty", b =>
                {
                    b.Navigation("warranty_details");
                });
#pragma warning restore 612, 618
        }
    }
}
